# Generated by Django 2.1.5 on 2019-04-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='org_id',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
